### ISSUE TITLE
Use Multiple component( label and textbox) in the one cell in ag-grid with angular 2 typescript.

### ISSUE THREAD

**Issue by KAfroz** [ag-grid/ag-grid-angular-example#47]
In Angular 2 application we have used the ag-grid to display the data.
Currently we want to use two html component in one cell(label and textbox) and when we click on the button it will show the updated textbox value and label value of the cell.

we have tried the following approach:
1.Cell Renderer
	we have used the cell renderer in which we are able to put two html component( label and textbox). in this case both html component are visible. but when we update the value on textbox the updated value can not be shown or get in typescript.

2. Cell editor
	We have used the cell editor in this case when are creating a component then only one html component is shown. Here on textbox we are able to get the udpated value on click of button also in typescript.

please suggest any way so that both component can be shown and updated textbox value can be shown on button click.

**Comment by seanlandsman** [comment]
You can use either approach for this - a cell renderer should work fine.

I'm not sure why you cant get the updated value without seeing your code, but what you're describing should work fine.

Please post a question on stackoverflow (or our members forum : https://ag-grid.com/forum/forumdisplay.php?fid=5 if you're a customer) for further assistance
