### ISSUE TITLE
Radio button not working properly

### ISSUE THREAD

**Issue by aachman** [ag-grid/ag-grid-angular-example#49]
This is regarding the issue #46.
We have updated the plunker in which the issue has been reproduced.
Below is the link to the updated plunker:
https://plnkr.co/edit/YQ5Pk1fJT6kKYtf9dvky?p=preview

Below is the line that we missed to add before, now when we have added the below line in the template and the issue is reproduced.
"<form #testForm="ngForm" enctype="multipart/form-data" method="post" name="MainForm">"

We are doing the following operation: 

operation 1
when we are performing the following steps then radio button is not working properly.
->click on hide button
->click on disable button( in that case only first radio button disable not all)

operation2
When we perform the following step then radio button disable properly.
->click on enable button.
->click on disable button( in that case all the radion button is disabled)

we want operation1 should work properly as when we click on hide->disable button, it should disable all the radio button.

Kindly provide some suggestion to resolve this issue.

**Comment by seanlandsman** [comment]
This repo is for ag-Grid related issues - I'd suggest you post your question on the ng2 bootstrap repo/forum
