### ISSUE TITLE
Angular Date Filter using Calendar

### ISSUE THREAD

**Issue by garkuwa** [ag-grid/ag-grid-angular-example#52]
Hi,

Thanks a lot for your example. It was so difficult for me to implement  Grid Date Component in Angular 4 till I found your example. I have case, where I need to use calendar (something like https://github.com/kineticsocial/angularjs-datetime-picker) instead inputs for every date part (the reason is that standard one is supported only be Chrome). Also I was required to enable floating filter (https://www.ag-grid.com/javascript-grid-floating-filter-component/#gsc.tab=0). I faced 3 problems:

1) I removed 'this.params.onDateChanged()' from setDate(date: Date) method, otherwise I get 'maximum stack size exceeded ' exception.

1) When I click on floating filter, calendar is overlapped by grid body (it's because ag-header and ag-header-viewport classes  both have 'overflow:hidden'. Changing it causing another UI problems ). Moving picker outside grid body is not possible due to the Angular components principle (as I understand)

2) Changing floating filter doesn't reflect in 'usual filter' input and visa versa. As I understand I should implement Floating Filter separately, but I don't have idea about that. 

I hope for some help. Thank you!

**Comment by seanlandsman** [comment]
I'm afraid I'd need a plunker or similar to be able to assist you here - if you can provide a repo I'm happy to take a look

**Comment by seanlandsman** [comment]
Closed due to inactivity
