### ISSUE TITLE
Infinite scrolling Pagination

### ISSUE THREAD

**Issue by Bhawna14** [ag-grid/ag-grid-angular-example#56]
Hello all,

I need help in configuring pagination for ag - grid.
The data in the grid comes fine. But when i am clicking on the 'NEXT' for pagination. for a moment it goes to page 2 the automatically the whole grid is getting refreshed and the grid will again show data from 1-10, instead of 11-20.

I am using code which is available on the tutorial
  setRowData(allOfTheData) {
      this.gridOptions.datasource = {
          rowCount: null, // behave as infinite scroll
          getRows: function (params) {
              console.log('asking for ' + params.startRow + ' to ' + params.endRow);
              // At this point in your code, you would call the server, using $http if in AngularJS 1.x.
              // To make the demo look real, wait for 500ms before returning
              setTimeout( function() {
                  // take a slice of the total rows
                  var rowsThisPage = allOfTheData.slice(params.startRow, params.endRow);
                  // if on or after the last page, work out the last row.
                  var lastRow = -1;
                  if (allOfTheData.length <= params.endRow) {
                      lastRow = allOfTheData.length;
                  }
                  // call the success callback
                  params.successCallback(rowsThisPage, lastRow);
              }, 500);
          }
      };
      if (this.gridOptions.api !== undefined) {
      this.gridOptions.api.setDatasource(this.gridOptions.datasource);
      }
  }

Can somebody please tell me that why i am not getting correct data when i am clicking on NEXT?

**Comment by Bhawna14** [comment]
this.gridOptions = < GridOptions > {
          onGridReady: () => {
              this.gridOptions.api.setDatasource(this.gridOptions.datasource);
          }
        };
        this.gridOptions.columnDefs = this.columnOnGrid;
        this.gridOptions.rowData = this.rowDataGrid;
        this.gridOptions.enableSorting = true;
        this.gridOptions.enableColResize = true;
        this.gridOptions.pagination = true;
        this.gridOptions.paginationPageSize = 100;
        this.gridOptions.maxBlocksInCache=5,
        this.gridOptions.cacheOverflowSize=2;
        this.gridOptions.enableServerSideSorting= true;
        this.gridOptions.enableServerSideFilter= true;
        this.gridOptions.maxBlocksInCache= 2;
        this.gridOptions.domLayout ='autoHeight';
        this.gridOptions.rowModelType = 'infinite';
    
Above is the grid congifuration that i am using

**Comment by seanlandsman** [comment]
Please see https://github.com/ag-grid/ag-grid-angular-example/tree/latest/systemjs_aot/app/infinite-pagination for a working example of how this can be done

thanks

**Comment by roshenpo007** [comment]
https://github.com/ag-grid/ag-grid-angular-example/tree/latest/systemjs_aot/app/infinite-pagination  . looks like this link is broken. Pagination is not working after the ag-grid updated to V15.
