### ISSUE TITLE
Using typeahead (Angular 1.5)control inside ag-grid cell.

### ISSUE THREAD

**Issue by child-of-god** [ag-grid/ag-grid-angular-example#61]
Hi All,
I have a requirement to integrate  typeahead control (ui.bootstrap.typeahead) in ag-grid cell. The application I am using is built on Angular 1.5. The demo in the documentation site is using ng2-typeahead (https://www.ag-grid.com/example-angular-third-party/?framework=all#typeahead_)which is an Angular 2 typeahead which wouldn't help. Can someone please help with a plnkr or jsfiddle.
Please find the plnkr demo : http://plnkr.co/edit/sbM5kewn8mD0w8qkv5ZO?p=preview
Thanks in advance.

**Comment by child-of-god** [comment]
I was able to achieve this , so closing the issue . The working demo is here http://plnkr.co/edit/sbM5kewn8mD0w8qkv5ZO?p=preview.

**Comment by amindolkar** [comment]
Hi @vishnunair639 the plnkr does not have anything. Can you please add the correct code?
