### ISSUE TITLE
How to set dropdowns on cells based on conditional check in aggrid angular 2 and above.

### ISSUE THREAD

**Issue by sushant47** [ag-grid/ag-grid-angular-example#62]
I have to set dropdowns to particular column.

But, I am able to set dropdowns for all cells of that column and my requirement is to show dropdown in particular cells based on conditional check.

kindly guide me or provide any code snippet if possible.

I am using angular version 4.3.5

**Comment by seanlandsman** [comment]
Please don't post support queries here. Use either stackoverflow.com, or if you're an Enterprise customer you can also use our Members Forum here: https://ag-grid.com/forum/forumdisplay.php?fid=5
