### ISSUE TITLE
Data getting overlapped when large amount of data loads

### ISSUE THREAD

**Issue by nilulande05** [ag-grid/ag-grid-angular-example#64]
We have used ag-grid v6.1.0 and facing issue of data overlapped. You need to scroll the data and sometimes it shows overlapped as per attached screenshot.
![data overlapped](https://user-images.githubusercontent.com/22637970/32647062-8f64da62-c615-11e7-9945-db55907e1f84.png)

**Comment by seanlandsman** [comment]
Hi,

Version 6.x is pretty old now - I'd suggest upgrading to the latest version and seeing if this resolves your issue.

thanks
