### ISSUE TITLE
Using Group Row Renderers

### ISSUE THREAD

**Issue by helloneoberg** [ag-grid/ag-grid-angular-example#65]
Hi, 
   i saw this screenshot in the URL: https://www.npmjs.com/package/ag-grid-angular#using-group-row-renderers.
   Can i know if this is free version o enterprise version?
   Thank you.

**Comment by seanlandsman** [comment]
Hi

Row grouping is an Enterprise feature - thanks !

regards,

**Comment by helloneoberg** [comment]
Hi,
   Noted with Thanks.
